name: Run tests and build (minified) script for web

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run CLI tests
        run: npm run test

      - name: Build minified version
        run: npm run build

      - name: Commit and push minified file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index-creator.min.js
          git diff --cached --quiet || git commit -m "Auto-build minified script"
          git push origin HEAD:${{ github.head_ref }}
